import type { AuthorCategory, Work } from "@prisma/client";
import { WechatNoteImporter } from "@/components/admin/wechat-note-importer";

export function WorkForm({ action, work, categories, authorId }: { action: (data: FormData) => void | Promise<void>; work?: Work; categories: AuthorCategory[]; authorId: string }) {
  return <form action={action} className="mt-8 space-y-5">{!work ? <WechatNoteImporter /> : null}<input type="hidden" name="authorId" value={authorId} />{work ? <><input type="hidden" name="workId" value={work.id} /><input type="hidden" name="slug" value={work.slug} /></> : null}<Input label="作品名称" name="name" value={work?.name} /><label className="block text-sm font-medium">作者小分类<select className="field-input mt-2" name="authorCategoryId" defaultValue={work?.authorCategoryId ?? ""}><option value="">其他作品</option>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><Input label="直购价（元）" name="directPriceYuan" value={work ? String(work.directPriceCents / 100) : ""} /><Input label="转发价（元）" name="repostPriceYuan" value={work ? String(work.repostPriceCents / 100) : ""} /></div><div className="flex gap-6"><Check name="supportsLab" label="LAB" checked={work?.supportsLab ?? true} /><Check name="supportsWcglass" label="WCGlass" checked={work?.supportsWcglass ?? true} /></div><Area label="功能说明" name="features" value={work?.features} /><Area label="转发要求" name="repostRequirements" value={work?.repostRequirements} /><Area label="购买须知" name="purchaseNotes" value={work?.purchaseNotes} />{!work ? <Input label="初始版本" name="version" value="1.0.0" /> : null}<button className="primary-button" type="submit">{work ? "保存作品" : "保存并继续上传图片"}</button>{!work ? <p className="text-sm text-muted">保存后上传主图和预览图，作者可自行发布，无需管理员审核。</p> : null}</form>;
}

function Input({ label, name, value = "" }: { label: string; name: string; value?: string }) { return <label className="block text-sm font-medium">{label}<input className="field-input mt-2" name={name} defaultValue={value} required /></label>; }
function Area({ label, name, value = "" }: { label: string; name: string; value?: string }) { return <label className="block text-sm font-medium">{label}<textarea className="field-input mt-2 min-h-24 py-3" name={name} defaultValue={value} required /></label>; }
function Check({ name, label, checked }: { name: string; label: string; checked: boolean }) { return <label className="flex items-center gap-2 text-sm"><input type="checkbox" name={name} defaultChecked={checked} />{label}</label>; }
